services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_URL=http://ollama:11434/v1/
      - NODE_ENV=production
      - OLLAMA_ENABLED=true
      - DEFAULT_ACCESS_TOKEN=testing
    depends_on:
      - ollama
    networks:
      - ollama-net

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - ollama-net
    entrypoint: /bin/sh
    command: -c "ollama serve & sleep 5 && ollama pull qwen3:1.7b && ollama pull llama3.2:latest && wait"

volumes:
  ollama-data:

networks:
  ollama-net:
    driver: bridge 