services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_URL=http://ollama:11434/v1/
      - NODE_ENV=production
      - OLLAMA_ENABLED=true
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - ollama-net

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - ollama-net
    entrypoint: /bin/sh
    command: -c "ollama serve & sleep 5 && ollama pull gemma3:4b && wait"

volumes:
  ollama-data:

networks:
  ollama-net:
    driver: bridge 